### ISSUE TITLE
天翼云盘 报错

### ISSUE THREAD

**Issue by aikunzhe** [mengshouer/CheckinBox#10]
![image](https://user-images.githubusercontent.com/9932394/98190820-db2ef880-1f52-11eb-80a8-b1930a92c73d.png)
E: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/bionic/InRelease  402  Payment Required [IP: 54.183.38.243 443]
E: The repository 'https://packagecloud.io/github/git-lfs/ubuntu bionic InRelease' is no longer signed.
Error: Process completed with exit code 100.

**Comment by mengshouer** [comment]
更新仓库
