### ISSUE TITLE
求个: 有道云 百度贴吧 的签到

### ISSUE THREAD

**Issue by ipme** [mengshouer/CheckinBox#11]
现在的腾讯函数 好像 要收费了吧
求个 百度贴吧, 有道云笔记 的签到

**Comment by mengshouer** [comment]
看了下计费，不是特别大流量的话应该不收费，每月都没到小数点的后两位，不放心的话可以到明细账单里查询
百度签到github上面挺多的，我自己也用的别人的。有道云的话倒是写完了，但是cookie没想到比较好的方法保存，每天登陆的话微信提醒有点烦，反正最近一个月我应该是没时间弄这些东西的(有事

**Comment by mengshouer** [comment]
github上面挺多贴吧签到的(鸽了，随便在上面找个能用的就行了.jpg
