### ISSUE TITLE
建议完善打印信息

### ISSUE THREAD

**Issue by RC1844** [mengshouer/CheckinBox#12]
比如说xxx开始签到
xxx签到完成
否则都不知道是那个账密有误

**Comment by mengshouer** [comment]
f583a52dd3506f16d06f508d11d63d7a92164106

**Comment by RC1844** [comment]
效率真高

**Comment by RC1844** [comment]
@mengshouer 那个，我再bb一下

> {"error_code":0,"error_msg":"","data":{"add_point":0,"checkin_num":"2","point":0,"exp":0,"gold":0,"prestige":0,"rank":0,"slogan":"<div class=\"signIn_data\">\u4eca\u65e5\u5df2\u9886<span class=\"red\">0<\/span>\u79ef\u5206\uff0c\u518d\u7b7e\u5230<span class=\"red\">1<\/span>\u5929\u53ef\u9886<span class=\"red\">0<\/span>\u79ef\u5206<\/div>","cards":0,"can_contract":0,"continue_checkin_days":2,"continue_checkin_reward_show":false}}

这个Unicode 编码转一下中文再打印

**Comment by mengshouer** [comment]
e886cc3fa9e73a1e90de3ee25d1c2bb353cc138b
现在没啥空，到时候再整理获取到的信息

**Comment by RC1844** [comment]
👍
