### ISSUE TITLE
天翼云盘这几天都是“抽奖次数不足”或者是“抽奖获得  0 ”

### ISSUE THREAD

**Issue by wy1ng** [mengshouer/CheckinBox#13]
签到时正常的，请问大家有遇到同样的问题吗？

**Comment by wy1ng** [comment]
Starting new HTTPS connection (1): api.cloud.189.cn:443

https://api.cloud.189.cn:443 "GET /mkt/userSign.action?rand=1605760896642&clientType=TELEANDROID&version=8.6.3&model=SM-G930K HTTP/1.1" 200 107

已经签到过了，签到获得  20  M空间

Starting new HTTPS connection (1): m.cloud.189.cn:443

https://m.cloud.189.cn:443 "GET /v2/drawPrizeMarketDetails.action?taskId=TASK_SIGNIN&activityId=ACT_SIGNIN HTTP/1.1" 200 141

抽奖次数不足

https://m.cloud.189.cn:443 "GET /v2/drawPrizeMarketDetails.action?taskId=TASK_SIGNIN_PHOTOS&activityId=ACT_SIGNIN HTTP/1.1" 200 252

抽奖获得  0

**Comment by mengshouer** [comment]
看了一眼获取记录。虽然日志有问题，但是实际获得的奖励没问题。过段时间我再改改

**Comment by wy1ng** [comment]
> 看了一眼获取记录。虽然日志有问题，但是实际获得的奖励没问题。过段时间我再改改

登上网盘看了看成长记录，抽奖确实是正常的！感谢！
