### ISSUE TITLE
网抑云

### ISSUE THREAD

**Issue by chuan01** [mengshouer/CheckinBox#21]
部署了下，报错了，请问一下你自己部署的项目还正常吗？

**Comment by mengshouer** [comment]
正常

**Comment by chuan01** [comment]
请问你是部署哪一个地域呢？

**Comment by mengshouer** [comment]
和地域没关系，你可以试试直接跑在github actions上

**Comment by liumingye** [comment]
NetEase_Music_dailyForSCF.py  158行的main改成run试试

**Comment by mengshouer** [comment]
啊这，我看我SCF没问题，我以为没问题，看了一眼发现我没更新多账号的.jpg(自己用不到
