### ISSUE TITLE
52pojie腾讯云函数执行方法错误

### ISSUE THREAD

**Issue by MaKemG** [mengshouer/CheckinBox#23]
不知道怎么弄了[image](https://user-images.githubusercontent.com/50041810/106784375-2afd8880-6644-11eb-97a8-2192fd59c66e.png)

**Comment by mengshouer** [comment]
执行方法是index.pjCheckin，忘记改了(代码直接copy的
还有52pj大概把腾讯云的ip段都封了，大概率会报403，要跑52pj的话直接用github的ac跑，改多几个时间段，总有成功的(

**Comment by MaKemG** [comment]
谢谢大佬了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "雪狐"<notifications@github.com&gt;; 
发送时间: 2021年2月4日(星期四) 上午10:26
收件人: "mengshouer/CheckinBox"<CheckinBox@noreply.github.com&gt;; 
抄送: "̶ᴍ̶̶ᵃ̶̶ᴋ̶̶ᵉ̶̶ᵐ̶"<1731276509@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [mengshouer/CheckinBox] 52pojie腾讯云函数执行方法错误 (#23)





 
执行方法是index.pjCheckin，忘记改了(代码直接copy的
 还有52pj大概把腾讯云的ip段都封了，大概率会报403，要跑52pj的话直接用github的ac跑，改多几个时间段，总有成功的(
