### ISSUE TITLE
可否添加telegram自建bot的提醒

### ISSUE THREAD

**Issue by iSteveyang** [mengshouer/CheckinBox#27]
sever酱挺好，多个tele更好
就像[这种](https://github.com/JunzhouLiu/BILIBILI-HELPER/pull/308)
向往能够PR

**Comment by mengshouer** [comment]
https://github.com/mengshouer/CheckinBox/commit/c3ad5fb6c5e4f7fe3d38f3fea75b2d49d955b0cc

**Comment by iSteveyang** [comment]
感谢，看到项目fork 有2.6k，详细看了下有几个人写的教程通俗易懂，也开了博客进行分享。
如果大佬有空，可以写点详细教程来宣传，增加star
当然这仅是建议

**Comment by mengshouer** [comment]
fork没啥用(个人感觉上没啥人用，有bug过了好长时间才有一个issue(

**Comment by iSteveyang** [comment]
要issue？我来了！
昨天 merge 好最新的pull request，tele的bot在今天给我发了消息

> 天翼云签到出错： ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='m.cloud.189.cn', port=443): Read timed out. (read timeout=20)”))

我一看workflow里run：

```
Run python3 ./Cloud189Checkin/C189CheckinForSCF.py
40
----------天翼云盘开始尝试签到----------
41
登录成功
42
已经签到过了，签到获得  78  M空间
43
天翼云签到出错： ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='m.cloud.189.cn', port=443): Read timed out. (read timeout=20)"))
44
----------天翼云盘签到执行完毕----------
```

我设定的是每天执行一次，也没有设定52pojie的secret，这咋出现了那么多次。。。

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/20753221/114569100-45d52480-9ca7-11eb-8c04-cc1029c47bb4.png">

**Comment by iSteveyang** [comment]
我那段话没描述清楚，你的fork里有人没改什么代码，而是自己开博客写教程，最后吸引流量star比你多，这让我觉得无奈。。。

**Comment by mengshouer** [comment]
52pojie是定时任务，看着烦也可以手动disable，就不会跑了。

天翼云盘还是推荐腾讯云函数跑，毕竟github actions运行的服务器实际上是在美国。

**Comment by iSteveyang** [comment]
好的，谢谢
