### ISSUE TITLE
签到失败

### ISSUE THREAD

**Issue by DollyDino9** [mengshouer/CheckinBox#28]
智友邦签到跟吾爱均签到失败_下面是运行日志。
Run python3 ./Cloud189Checkin/C189CheckinForSCF.py
----------52pojie开始尝试签到----------
52pj出错
----------52pojie签到执行完毕----------
----------智友邦开始尝试签到----------
第 1 个账号开始执行任务
您今日已经签到，请明天再来！
----------智友邦签到执行完毕----------

**Comment by mengshouer** [comment]
吾爱是大概是ip风控，没啥好的解决办法，只能把吾爱的运行触发单独出来，自己设置不同时间运行吧(

**Comment by mengshouer** [comment]
https://github.com/mengshouer/CheckinBox/commit/7ca624da70700f2ae73bf1f4adba8a432c12321d
