### ISSUE TITLE
可否添加吾爱的免费评分和自动回帖

### ISSUE THREAD

**Issue by xiaoming140** [mengshouer/CheckinBox#31]
因为吾爱会定时清理不活跃账号，有时又忘了。感谢大佬

**Comment by mengshouer** [comment]
https://github.com/mengshouer/CheckinBox/commit/edc26a086aa98dbe8886ab29a8f72990dc557c5a

只添加了免费评分，自动回帖不会考虑添加，避免无意义灌水。
