### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by xiaoming140** [mengshouer/CheckinBox#33]
好像网易云可以一次刷510首
#大佬，怎么更新fork的仓库啊

**Comment by mengshouer** [comment]
网易云刷歌是看账号的吧，而且我网易云用的少，我自己刷歌都感觉没啥用了吧，现在没几个人会缺这个，缺的都是天数。

更新fork的仓库，ReadMe里面有写，1.可以使用bot插件自动更新。2. 用pr功能手动从我仓库拉到你那里 3. 自己的库拉到本地，然后更新后自行提交。
