### ISSUE TITLE
可以添加一个小猿搜题的签到吗

### ISSUE THREAD

**Issue by lintao140** [mengshouer/CheckinBox#36]
![Screenshot_2021-05-05-14-58-03-389_com fenbi android solar](https://user-images.githubusercontent.com/83452272/117106380-6132cd00-ad45-11eb-9430-f5e168d8f023.jpg)
![Screenshot_2021-05-05-14-57-58-187_com fenbi android solar](https://user-images.githubusercontent.com/83452272/117106385-642dbd80-ad45-11eb-82db-74428e976c4d.jpg)
# 挺想要这个明信片的，可是学生又不能打卡，麻烦大佬了。

**Comment by mengshouer** [comment]
自己用不上(大概率是没精力去加了
