### ISSUE TITLE
出错了

### ISSUE THREAD

**Issue by 888haobing** [mengshouer/CheckinBox#37]
本来还好好好的，一更新，成这样了
![screenshot-github-com-888haobing-CheckinBox-runs-2589831661-1621070646988](https://user-images.githubusercontent.com/76923303/118355407-73f99d00-b5a2-11eb-8b61-b53f676247e0.png)
可是我只有1个账号啊

**Comment by mengshouer** [comment]
我自己的没啥问题，你更新一下secrets看看？
