### ISSUE TITLE
FF14Checkin运行报错

### ISSUE THREAD

**Issue by Apostilize** [mengshouer/CheckinBox#40]
腾讯云SCF运行的

{
  "errorCode": -1,
  "errorMessage": "user code exception caught",
  "requestId": "898c87ed-b602-417e-bfe1-e4adfb6f53ef",
  "stackTrace": "Traceback (most recent call last):\n  File \"/var/user/index.py\", line 224, in go\n    if \"\\\\n\" in login_name:\nTypeError: argument of type 'NoneType' is not iterable",
  "statusCode": 430
}

**Comment by mengshouer** [comment]
edbe171b64a57f1e1f7e6ae3f580f703e12bad76

忘记改说明了，不过腾讯云上面真的很大概率出验证码(不是常用环境都会出

**Comment by Apostilize** [comment]
> [edbe171](https://github.com/mengshouer/CheckinBox/commit/edbe171b64a57f1e1f7e6ae3f580f703e12bad76)
> 
> 忘记改说明了，不过腾讯云上面真的很大概率出验证码(不是常用环境都会出

已经成功运行两天，我没怎么在网页上登录过盛大账号，一般都会让我输验证码，但是现在部署到SCF就没验证码了，真的很神奇
