### ISSUE TITLE
天翼网盘 189 Cloud 修复方法

### ISSUE THREAD

**Issue by BlueSkyXN** [mengshouer/CheckinBox#42]
参考：https://github.com/BlueSkyXN/189Cloud-Checkin
把你脚本的登陆URL改一下就行

**Comment by luoxuye** [comment]
keyi  dalao nb!

**Comment by mengshouer** [comment]
098fa9854c7667f9272394aa11208d74187647e8 改了，github已经不提示我这个项目的issue了(
