### ISSUE TITLE
恩山-腾讯云函数 失败

### ISSUE THREAD

**Issue by whx1024** [mengshouer/CheckinBox#47]
cookie是新抓的，但第一个晚上就失效了，问问
云函数是广东区的
日志：

START RequestId:401a64de-e318-444a-8f84-e3f232d9ab75

Starting new HTTPS connection (1): www.right.com.cn:443

https://www.right.com.cn:443 "GET /forum/home.php?mod=spacecp&ac=credit&op=log&suboperation=creditrulelog HTTP/1.1" 200 None

第 1 个账号开始执行任务

恩山论坛签到失败，可能是cookie失效了！

Response RequestId:401a64de-e318-444a-8f84-e3f232d9ab75 RetMsg:"\u7b2c 1 \u4e2a\u8d26\u53f7\u5f00\u59cb\u6267\u884c\u4efb\u52a1\n\u6069\u5c71\u8bba\u575b\u7b7e\u5230\u5931\u8d25\uff0c\u53ef\u80fd\u662fcookie\u5931\u6548\u4e86\uff01"

END RequestId:401a64de-e318-444a-8f84-e3f232d9ab75

Report RequestId:401a64de-e318-444a-8f84-e3f232d9ab75 Duration:278ms Memory:128MB MemUsage:17.847656MB

**Comment by mengshouer** [comment]
大概率是没访问到网站，有时候我本地访问的时候都会访问不到，推荐换个地域(我自己是在github的，action用的是境外的ip，我倒是好久没遇到过访问不到了)，小概率是cookie没抓全，随便点个帖子再拿cookie

**Comment by whx1024** [comment]
好的！我再试试！
