### ISSUE TITLE
提示列表索引超出范围

### ISSUE THREAD

**Issue by wsaddede** [mengshouer/CheckinBox#49]
测试提示"第 1 个账号开始执行任务\n天翼云签到出错：IndexError;('list index out of range',)\n"
不知道哪里出问题了

**Comment by mengshouer** [comment]
大概是账号密码没对应吧

**Comment by wsaddede** [comment]
我重新测试了下，是API的问题，换掉了  

从 Windows 版邮件发送

发件人: 雪狐
发送时间: 2021年9月9日 0:12
收件人: mengshouer/CheckinBox
抄送: sandral; Author
主题: Re: [mengshouer/CheckinBox] 提示列表索引超出范围 (#49)

大概是账号密码没对应吧
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
