### ISSUE TITLE
52破解SCF签到成功，无推送

### ISSUE THREAD

**Issue by loa123** [mengshouer/CheckinBox#54]
**注释掉下面的代码，并手动安装requirements.txt**
```
requests.packages.urllib3.disable_warnings()
```

**及**

```
try:
from notify import send as pusher
except:
logger.info("无青龙推送文件")
```

**设定固定IP**
就签到成功了，但是没有推送成功的代码，请酌情修复下，谢谢

**附下log**
```
第 1 个账号开始执行任务
签到成功
----------52pojie签到执行完毕----------
```

**Comment by mengshouer** [comment]
签到成功正常就是不推送的，还有我记得之前52破解屏蔽了大部分SCF的IP，导致经常会签到失败，所以也没加推送错误提示。

**Comment by loa123** [comment]
> 签到成功正常就是不推送的，还有我记得之前52破解屏蔽了大部分SCF的IP，导致经常会签到失败，所以也没加推送错误提示。

我觉得屏蔽的可能是公共IP地址池，固定IP（国内）应该还是不屏蔽的，我这次用的是广州的固定IP，你可以试试

加推送的话我觉得挺方便，一天一次

**Comment by mengshouer** [comment]
> > 签到成功正常就是不推送的，还有我记得之前52破解屏蔽了大部分SCF的IP，导致经常会签到失败，所以也没加推送错误提示。
> 
> 我觉得屏蔽的可能是公共IP地址池，固定IP（国内）应该还是不屏蔽的，我这次用的是广州的固定IP，你可以试试
> 
> 加推送的话我觉得挺方便，一天一次

我就是不想被打扰所以才没加(

你要加的话可以直接在128行加个pusher(msg)
